apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: demo-deployment
spec:
  # 3 Pods should exist at all times.
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nginx
    spec:
      containers:
      - name: nginx
        # Run this image
        image: nginx:1.14
