apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-15T02:26:00Z"
  generateName: hello-27587666--1-
  labels:
    controller-uid: 3f4b98e0-ac0a-4abf-bd02-d1cd5ca64550
    job-name: hello-27587666
  name: hello-27587666--1-p7jvz
  namespace: default
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: hello-27587666
    uid: 3f4b98e0-ac0a-4abf-bd02-d1cd5ca64550
  resourceVersion: "2223148"
  uid: 6a10465e-c0f3-4067-8153-e59e2061fad6
spec:
  containers:
  - command:
    - echo
    - Hello World
    - -o
    - yaml
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: hello
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rzls2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-agentpool-14442275-vmss000001
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-rzls2
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-06-15T02:26:00Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-06-15T02:26:00Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-06-15T02:26:00Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-06-15T02:26:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://78fda8811d1af6ae935f5c94649f9c1929abfe9b97dd35b04c36ac12a1215b2b
    image: docker.io/library/busybox:1.28
    imageID: docker.io/library/busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
    lastState: {}
    name: hello
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://78fda8811d1af6ae935f5c94649f9c1929abfe9b97dd35b04c36ac12a1215b2b
        exitCode: 0
        finishedAt: "2022-06-15T02:26:01Z"
        reason: Completed
        startedAt: "2022-06-15T02:26:01Z"
  hostIP: 10.240.0.115
  phase: Succeeded
  podIP: 10.240.0.119
  podIPs:
  - ip: 10.240.0.119
  qosClass: BestEffort
  startTime: "2022-06-15T02:26:00Z"
